Add Iris, Sacha & Karen.
antistatique/humans.txt pull request #17
Opened 2020-09-07 07:53 UTC by yannlugrin

2020-09-07 08:00 UTC, iwolfisberg approved these changes

2020-09-07 08:53 UTC, sachatissot requested changes

2020-09-07 08:53 UTC, sachatissot commented on humans.txt
> +  From: Saint-Julien-en-Genevois, Switzerland
```suggestion
  From: Saint-Julien-en-Genevois, France
```

2020-09-07 08:58 UTC, karentschanz0 approved these changes

2020-09-07 08:58 UTC, merged

2020-09-11 12:20 UTC, sachatissot reviewed
OK POUR MOI